-- 주문량이 많은 아이스크림들 조회하기 | X
-- WHERE로 따로 만들지 않고, JOIN을 할 때 곧바로 새로 정리한 테이블을 넣어 쓸 수 있다.
SELECT F.FLAVOR
FROM FIRST_HALF F 
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM JULY
      GROUP BY FLAVOR) J
ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3;