-- 상위 n개 레코드 | O
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1; 
-- 상위 N개의 레코드는 LIMIT을 이용해 그 갯수를 지정할 수 있다.

-- 여러 기준으로 정렬하기 | O
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC;

-- 어린 동물 찾기 | X
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NOT INTAKE_CONDITION = 'Aged'
ORDER BY ANIMAL_ID;
-- INTAKE_CONDITION이 Aged가 아닌 것을 찾는다.