-- 나이 정보가 없는 회원 수 구하기 | O
SELECT COUNT (*) AS USERS
FROM USER_INFO
WHERE AGE IS NULL;


-- 가장 비싼 상품 구하기 | X
SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT


-- 경기도에 위치한 식품창고 목록 출력하기 | X
-- FREEZER_YN이 NULL이면 "N"을 출력한다.
-- 주소가 "~경기~"인 것만 찾는다. 
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE "%경기%"
ORDER BY WAREHOUSE_ID