-- 5월 식품들의 총매출 조회하기 | O
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE "2022-05%"
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID


-- 취소되지 않은 진료 예약 조회하기 | X
-- ✅ 테이블 3개 JOIN 유형
-- ✅ 먼저 두개를 조인 후, 하나를 조인해준다.  
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A INNER JOIN PATIENT P ON A.PT_NO = P.PT_NO
INNER JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE A.MCDP_CD = 'CS' AND A.APNT_YMD LIKE "2022-04-13%" AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD


-- 년, 월, 성별 별 상품 구매 회원 수 구하기 | X
-- '동일한 날짜, 회원 ID, 상품 ID 조합에 대해서는 하나의 판매 데이터만 존재합니다' => DISTINCT로 중복을 없애주어야 한다.
SELECT YEAR(SALES_DATE) AS YEAR, 
		MONTH(SALES_DATE) AS MONTH, 
        GENDER, 
        COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE O INNER JOIN USER_INFO U 
ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;