-- 동물의 아이디와 이름 | O
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;


-- 이름이 없는 동물의 아이디 | O
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
-- ORDER BY ANIMAL_ID;


-- 이름이 있는 동물의 아이디 | O
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID;


-- 역순 정렬하기 | O
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;


-- 아픈 동물 찾기 | O
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID;