-- 조건에 맞는 아이템들의 가격의 총합 구하기 | O | Lv2
SELECT SUM(PRICE) AS TOTAL_PRICE
FROM ITEM_INFO
WHERE RARITY = 'LEGEND';


-- 물고기 종류별 잡은 수 구하기 | O | Lv2
-- ✅ FISH_TYPE을 이용해 두 테이블을 JOIN한 후, 각 타입별 잡은 물고기 수를 COUNT해 FISH_NAME으로 묶는다. 
SELECT COUNT(B.FISH_TYPE) AS FISH_COUNT, B.FISH_NAME
FROM FISH_INFO AS A INNER JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_NAME
ORDER BY FISH_COUNT DESC;


-- ROOT 아이템 구하기 | O | Lv2
-- ROOT 아이템을 구하려면, PARENT_ITEM_ID이 NULL인 값을 찾아 출력하면 된다.
SELECT A.ITEM_ID, A.ITEM_NAME
FROM ITEM_INFO AS A INNER JOIN ITEM_TREE AS B
ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID;


-- 연도 별 평균 미세먼지 농도 조회하기 | O | Lv2
SELECT YEAR(YM) AS YEAR, ROUND(AVG(PM_VAL1), 2) AS PM10, ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원'
GROUP BY YEAR
ORDER BY YEAR